fix : some fix

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,6 +1,6 @@
 #!/bin/bash
 # author : lordpax
-# backup v3.3.2
+# backup v3.3.3
 # Petit script de backup
 
 export TEXTDOMAIN="backup"
@@ -11,7 +11,7 @@ backup_folders=""
 backup_dest="."
 log=0
 logFile=""
-version="v3.3.2"
+version="v3.3.3"
 archive_name=""
 verbose=0
 nbToSave=0
@@ -22,31 +22,28 @@ url=""
 
 # echo_deb <msg>
 function echo_log() {
-    if [ "A$1" != "A" ] && [ "A$logFile" != "A" ]; then
-        local date=$(date "+%Y-%m-%d %H:%M:%S")
-        echo -e "$date : $1" >> $logFile
-    fi
+    ([ "$1" == "" ] || [ "$logFile" == "" ]) && exit 1
+    local date=$(date "+%Y-%m-%d %H:%M:%S")
+    echo -e "$date : $1" >> $logFile
 }
 
 # echo_err <msg>
 function echo_err() {
-    if [ "A$1" != "A" ]; then
-        if [ $log -eq 1 ]; then
-            echo_log "ERROR : $1"
-        else
-            echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
-        fi
+    [ "$1" == "" ] && exit 1
+    if [ $log -eq 1 ]; then
+        echo_log "ERROR : $1"
+    else
+        echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
     fi
 }
 
 # echo_out <msg>
 function echo_out() {
-    if [ "A$1" != "A" ]; then
-        if [ $log -eq 1 ]; then
-            echo_log "$1" 
-        else
-            echo -e "$1"
-        fi
+    [ "$1" == "" ] && exit 1
+    if [ $log -eq 1 ]; then
+        echo_log "$1" 
+    else
+        echo -e "$1"
     fi
 }
 
@@ -82,7 +79,7 @@ function verification() {
     date=$(date +%Y-%m-%d)
     # hostname=$(hostname -s)
     hostname=$(hostnamectl hostname)
-    out=$(([ $log -eq 1 ] || [ $verbose -eq 0 ]) && echo /dev/null || echo /dev/stdout)
+    out=$( ([ $log -eq 1 ] || [ $verbose -eq 0 ]) && echo /dev/null || echo /dev/stdout)
 
     if [ "A$tmp_folders" != "A" ]; then
         for file in $tmp_folders; do
@@ -116,11 +113,10 @@ function verification() {
 
 # readConfig <config>
 function readConfig() {
-    if [ "A$1" != "A" ]; then
-        while read line; do
-            tmp_folders="$tmp_folders $line"
-        done < $1
-    fi
+    [ "$1" == "" ] && echo_err $"Parameter needed for readConfig" && exit 1
+    while read line; do
+        tmp_folders="$tmp_folders $line"
+    done < $1
 }
 
 function encryptFile() {
@@ -142,18 +138,15 @@ function encryptFile() {
 
 # decryptFile <encryptedFile>
 function decryptFile() {
-    if [ "A$1" != "A" ]; then
-        local crypted_file=$1
-        echo_out $"Decryption of $crypted_file.aes ..."
-        if ! aescrypt -d $crypted_file.aes &> $out; then
-            echo_err $"Something wrong with decryption"
-            exit 1
-        fi
-        echo_out $"Decryption $crypted_file.aes end"
-    else
-        echo_err $"Encrypted file missing"
+    [ "$1" == "" ] && echo_err $"Encrypted file missing" && exit 1
+    local crypted_file=$1
+
+    echo_out $"Decryption of $crypted_file.aes ..."
+    if ! aescrypt -d $crypted_file.aes &> $out; then
+        echo_err $"Something wrong with decryption"
         exit 1
     fi
+    echo_out $"Decryption $crypted_file.aes end"
 }
 
 function compressFile() {
@@ -176,22 +169,21 @@ function compressFile() {
 # delete <nbToSave>
 # conserve les nbToSave les plus récentes et supprime les autres
 function delete() {
-    if [ "A$1" != "A" ]; then
-        local name=$([ "A$archive_name" != "A" ] && echo "$archive_name" || echo "backup_${hostname}")
-        local nbFile=$(ls $backup_dest | grep $name | wc -l)
-        local nbToDel=$(( nbFile - $1 ))
-        local extEnc=$([ $encrypt -eq 1 ] && echo ".aes" || echo "")
+    [ "$1" == "" ] && echo_err $"Parameter needed for delete" && exit 1
+    local name=$([ "A$archive_name" != "A" ] && echo "$archive_name" || echo "backup_${hostname}")
+    local nbFile=$(ls $backup_dest | grep $name | wc -l)
+    local nbToDel=$(( nbFile - $1 ))
+    local extEnc=$([ $encrypt -eq 1 ] && echo ".aes" || echo "")
 
-        if [ $nbToDel -gt 0 ]; then 
-            local archive_date=$(ls $backup_dest | grep $name | cut -d '.' -f 2 | sort -r | tail -$nbToDel)
+    if [ $nbToDel -gt 0 ]; then 
+        local archive_date=$(ls $backup_dest | grep $name | cut -d '.' -f 2 | sort -r | tail -$nbToDel)
 
-            echo_out "Deleting $nbToDel old backup : "
-            
-            for elem in $archive_date; do
-                echo_out "  -> Deleting $backup_dest/${name}.${elem}.tar.gz$extEnc ..."
-                rm $backup_dest/${name}.${elem}.tar.gz$extEnc
-            done
-        fi
+        echo_out "Deleting $nbToDel old backup : "
+
+        for elem in $archive_date; do
+            echo_out "  -> Deleting $backup_dest/${name}.${elem}.tar.gz$extEnc ..."
+            rm $backup_dest/${name}.${elem}.tar.gz$extEnc
+        done
     fi
 }
 
@@ -202,12 +194,8 @@ function restoreFile() {
     local archive_ext=$(ls $backup_folders | grep $name | cut -d '.' -f 5 | sort -r | head -1)
     local full_name="$backup_folders/${name}.${archive_date}.tar.gz"
 
-    if [ "A$archive_date" == "A" ]; then
-        echo_err $"No backup found"
-        exit 1
-    fi
-    
-    [ "A$archive_ext" == "Aaes" ] && decryptFile $full_name
+    [ "$archive_date" == "" ] && echo_err $"No backup found" && exit 1
+    [ "$archive_ext" == "aes" ] && decryptFile $full_name
     
     echo_out $"Restoration of $full_name to $backup_dest"
     if ! tar xfz $full_name -C $backup_dest &> $out; then
@@ -215,7 +203,7 @@ function restoreFile() {
         exit 1
     fi
 
-    if [ "A$archive_ext" == "Aaes" ]; then 
+    if [ "$archive_ext" == "aes" ]; then 
         echo_out $"Wiping of $full_name ..."
         if ! shred -zvu $full_name &> $out; then
             echo_err $"Something wrong with wiping"
@@ -269,36 +257,35 @@ if [ $# -ge 1 ]; then
                 echo_out $version
                 exit 0;;
             -f)
-                shift
-                tmp_folders=$1;;
+                tmp_folders=$2
+                shift;;
             -r)
-                shift
                 restore=1
-                tmp_folders=$1;;
+                tmp_folders=$2
+                shift;;
             -o)
-                shift
-                backup_dest=$1;;
+                backup_dest=$2
+                shift;;
             -c)
-                shift
-                readConfig $1;;
+                readConfig $2
+                shift;;
             -l)
-                shift
                 log=1
-                logFile=$1;;
+                logFile=$2
+                shift;;
             -e)
                 encrypt=1;;
             -n)
-                shift
-                archive_name=$1;;
-            -s)
-                shift
-                nbToSave=$1;;
-            -g)
-                shift 
-                gitmode=1
-                readConfig $1
-                branch=$2
+                archive_name=$2
                 shift;;
+            -s)
+                nbToSave=$2
+                shift;;
+            -g)
+                gitmode=1
+                readConfig $2
+                branch=$3
+                shift 2;;
             "")
                 ;;
             *)
